/* =========================================================
   CAT TIMES
   Supabase Database Schema
   Version 3
   ========================================================= */


/* =========================================================
   1. EXTENSIONS
   ========================================================= */

create extension if not exists pgcrypto;


/* =========================================================
   2. POSTS
   ========================================================= */

create table if not exists public.posts (

  id bigint generated by default as identity
    primary key,

  nickname text
    not null
    default '匿名用户',

  title text
    not null,

  category text
    not null,

  content text
    not null,

  status text
    not null
    default 'published',

  like_count integer
    not null
    default 0,

  created_at timestamptz
    not null
    default now(),

  updated_at timestamptz
    not null
    default now(),

  constraint posts_nickname_length
    check (
      char_length(nickname)
      between 1 and 30
    ),

  constraint posts_title_length
    check (
      char_length(title)
      between 1 and 100
    ),

  constraint posts_content_length
    check (
      char_length(content)
      between 1 and 5000
    ),

  constraint posts_category_check
    check (
      category in (
        '校园生活',
        '学习压力',
        '食堂住宿',
        '老师教学',
        '社团活动',
        '校园设施',
        '其他'
      )
    ),

  constraint posts_status_check
    check (
      status in (
        'published',
        'hidden',
        'deleted'
      )
    ),

  constraint posts_like_count_check
    check (
      like_count >= 0
    )

);


/* =========================================================
   3. COMMENTS
   ========================================================= */

create table if not exists public.comments (

  id bigint generated by default as identity
    primary key,

  post_id bigint
    not null
    references public.posts(id)
    on delete cascade,

  nickname text
    not null
    default '匿名用户',

  content text
    not null,

  status text
    not null
    default 'published',

  created_at timestamptz
    not null
    default now(),

  updated_at timestamptz
    not null
    default now(),

  constraint comments_nickname_length
    check (
      char_length(nickname)
      between 1 and 30
    ),

  constraint comments_content_length
    check (
      char_length(content)
      between 1 and 500
    ),

  constraint comments_status_check
    check (
      status in (
        'published',
        'hidden',
        'deleted'
      )
    )

);


/* =========================================================
   4. REACTIONS
   ========================================================= */

create table if not exists public.reactions (

  id bigint generated by default as identity
    primary key,

  post_id bigint
    not null
    references public.posts(id)
    on delete cascade,

  visitor_id uuid
    not null,

  type text
    not null
    default 'like',

  created_at timestamptz
    not null
    default now(),

  constraint reactions_type_check
    check (
      type = 'like'
    ),

  constraint reactions_unique_like
    unique (
      post_id,
      visitor_id,
      type
    )

);


/* =========================================================
   5. REPORTS
   ========================================================= */

create table if not exists public.reports (

  id bigint generated by default as identity
    primary key,

  post_id bigint
    not null
    references public.posts(id)
    on delete cascade,

  visitor_id uuid
    not null,

  reason text
    not null,

  created_at timestamptz
    not null
    default now(),

  constraint reports_reason_check
    check (
      reason in (
        'spam',
        'privacy',
        'harassment',
        'false_information',
        'other'
      )
    )

);


/* =========================================================
   6. INDEXES
   ========================================================= */

create index if not exists
  posts_created_at_idx
on public.posts (
  created_at desc
);


create index if not exists
  posts_category_created_at_idx
on public.posts (
  category,
  created_at desc
);


create index if not exists
  posts_status_created_at_idx
on public.posts (
  status,
  created_at desc
);


create index if not exists
  comments_post_created_at_idx
on public.comments (
  post_id,
  created_at asc
);


create index if not exists
  reactions_post_idx
on public.reactions (
  post_id
);


create index if not exists
  reactions_visitor_idx
on public.reactions (
  visitor_id
);


create index if not exists
  reports_post_idx
on public.reports (
  post_id
);


create index if not exists
  reports_created_at_idx
on public.reports (
  created_at desc
);


/* =========================================================
   7. UPDATED_AT FUNCTION
   ========================================================= */

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin

  new.updated_at = now();

  return new;

end;
$$;


/* =========================================================
   8. UPDATED_AT TRIGGERS
   ========================================================= */

drop trigger if exists
  posts_set_updated_at
on public.posts;


create trigger
  posts_set_updated_at

before update
on public.posts

for each row
execute function public.set_updated_at();


drop trigger if exists
  comments_set_updated_at
on public.comments;


create trigger
  comments_set_updated_at

before update
on public.comments

for each row
execute function public.set_updated_at();


/* =========================================================
   9. LIKE COUNT FUNCTIONS
   ========================================================= */

create or replace function public.increment_post_like_count()
returns trigger
language plpgsql
security invoker
as $$
begin

  update public.posts

  set like_count =
    like_count + 1

  where id = new.post_id;

  return new;

end;
$$;


create or replace function public.decrement_post_like_count()
returns trigger
language plpgsql
security invoker
as $$
begin

  update public.posts

  set like_count =
    greatest(
      like_count - 1,
      0
    )

  where id = old.post_id;

  return old;

end;
$$;


/* =========================================================
   10. LIKE COUNT TRIGGERS
   ========================================================= */

drop trigger if exists
  reactions_increment_like_count
on public.reactions;


create trigger
  reactions_increment_like_count

after insert
on public.reactions

for each row
execute function public.increment_post_like_count();


drop trigger if exists
  reactions_decrement_like_count
on public.reactions;


create trigger
  reactions_decrement_like_count

after delete
on public.reactions

for each row
execute function public.decrement_post_like_count();


/* =========================================================
   11. ENABLE RLS
   ========================================================= */

alter table public.posts
enable row level security;


alter table public.comments
enable row level security;


alter table public.reactions
enable row level security;


alter table public.reports
enable row level security;


/* =========================================================
   12. REMOVE OLD POLICIES
   ========================================================= */

drop policy if exists
  "posts_public_select"
on public.posts;


drop policy if exists
  "posts_public_insert"
on public.posts;


drop policy if exists
  "comments_public_select"
on public.comments;


drop policy if exists
  "comments_public_insert"
on public.comments;


drop policy if exists
  "reactions_public_insert"
on public.reactions;


drop policy if exists
  "reports_public_insert"
on public.reports;


/* =========================================================
   13. POSTS POLICIES
   ========================================================= */

/*
  Everyone can read published posts.
*/

create policy
  "posts_public_select"

on public.posts

for select

to anon, authenticated

using (
  status = 'published'
);


/*
  Visitors can create published posts.

  They cannot insert:
  hidden / deleted
  posts through the public browser API.
*/

create policy
  "posts_public_insert"

on public.posts

for insert

to anon, authenticated

with check (
  status = 'published'
);


/* =========================================================
   14. COMMENTS POLICIES
   ========================================================= */

/*
  Everyone can read published comments.
*/

create policy
  "comments_public_select"

on public.comments

for select

to anon, authenticated

using (
  status = 'published'
);


/*
  Everyone can create published comments.
*/

create policy
  "comments_public_insert"

on public.comments

for insert

to anon, authenticated

with check (
  status = 'published'
);


/* =========================================================
   15. REACTIONS POLICIES
   ========================================================= */

/*
  Visitors can insert likes.

  The unique constraint prevents the same
  visitor from liking the same post twice.
*/

create policy
  "reactions_public_insert"

on public.reactions

for insert

to anon, authenticated

with check (
  type = 'like'
);


/*
  IMPORTANT:
  No public SELECT policy is created for reactions.

  Visitors therefore cannot browse every visitor_id.

  The frontend keeps local like state in LocalStorage,
  while posts.like_count is maintained by triggers.
*/


/* =========================================================
   16. REPORT POLICIES
   ========================================================= */

/*
  Visitors may submit reports.
*/

create policy
  "reports_public_insert"

on public.reports

for insert

to anon, authenticated

with check (
  true
);


/*
  IMPORTANT:
  No SELECT policy for reports.

  Ordinary visitors cannot read reports.
*/


/* =========================================================
   17. GRANTS
   ========================================================= */

/*
  Supabase has changed Data API exposure behavior for
  newer projects. Explicit grants avoid the classic
  "permission denied for table" problem.
*/


/* POSTS */

grant select
on table public.posts
to anon, authenticated;


grant insert
on table public.posts
to anon, authenticated;


/* COMMENTS */

grant select
on table public.comments
to anon, authenticated;


grant insert
on table public.comments
to anon, authenticated;


/* REACTIONS */

grant insert
on table public.reactions
to anon, authenticated;


/* REPORTS */

grant insert
on table public.reports
to anon, authenticated;


/*
  Keep service_role privileges intact.

  service_role is server-side only and bypasses RLS.
*/


/* =========================================================
   18. SEQUENCE PRIVILEGES
   ========================================================= */

grant usage, select
on sequence public.posts_id_seq
to anon, authenticated;


grant usage, select
on sequence public.comments_id_seq
to anon, authenticated;


grant usage, select
on sequence public.reactions_id_seq
to anon, authenticated;


grant usage, select
on sequence public.reports_id_seq
to anon, authenticated;


/* =========================================================
   19. SECURITY HARDENING
   ========================================================= */

/*
  Do not allow anonymous users to update/delete rows.

  We intentionally do NOT grant:
    update
    delete

  to anon/authenticated.

  This means the public browser can:
    SELECT published posts
    INSERT posts
    SELECT published comments
    INSERT comments
    INSERT reactions
    INSERT reports

  but cannot directly:
    UPDATE posts
    DELETE posts
    UPDATE comments
    DELETE comments
    DELETE reactions
    READ reports
*/


/* =========================================================
   20. REPAIR LIKE COUNTS
   ========================================================= */

/*
  Run this if the database already had reactions
  before this schema was installed.
*/

update public.posts p

set like_count = (

  select count(*)::integer

  from public.reactions r

  where r.post_id = p.id

  and r.type = 'like'

);


/* =========================================================
   21. OPTIONAL DEFAULT PRIVILEGE HARDENING
   ========================================================= */

/*
  This section prevents future public tables from
  automatically receiving broad Data API privileges.

  Existing tables above already have explicit grants.

  If you create future public tables, grant only the
  permissions they actually need.
*/


alter default privileges
in schema public

revoke
  all
on tables
from anon, authenticated;


/* =========================================================
   END
   ========================================================= */
